{"name": "test_mul_004", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_file_003.Test_Credence_003 object at 0x0000025EB25D1C50>\n\n    def test_mul_004(self):\n        a = 3\n        b = 7\n        mul = a * b\n        print(\"Mul of a and b is :\" + str(mul))\n        if mul == 10:\n            assert True\n        else:\n>           assert False\nE           assert False\n\ntest_file_003.py:11: AssertionError"}, "start": 1690598798785, "stop": 1690598798786, "uuid": "5e6769ce-a1bd-4182-af83-a14715169aef", "historyId": "1da0023011657c42a38b1de108e70725", "testCaseId": "1da0023011657c42a38b1de108e70725", "fullName": "test_file_003.Test_Credence_003#test_mul_004", "labels": [{"name": "suite", "value": "test_file_003"}, {"name": "subSuite", "value": "Test_Credence_003"}, {"name": "host", "value": "Tushar-Pc"}, {"name": "thread", "value": "1496-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_file_003"}]}