{"name": "test_mul_004", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_file_003.Test_Credence_003 object at 0x000001F48CB49090>\n\n    def test_mul_004(self):\n        a = 3\n        b = 7\n        mul = a * b\n        print(\"Mul of a and b is :\" + str(mul))\n        if mul == 10:\n            assert True\n        else:\n>           assert False\nE           assert False\n\ntest_file_003.py:11: AssertionError"}, "start": 1690599159607, "stop": 1690599159607, "uuid": "f5a6444b-3cb0-4227-9a3b-bf4c19b8e774", "historyId": "1da0023011657c42a38b1de108e70725", "testCaseId": "1da0023011657c42a38b1de108e70725", "fullName": "test_file_003.Test_Credence_003#test_mul_004", "labels": [{"name": "suite", "value": "test_file_003"}, {"name": "subSuite", "value": "Test_Credence_003"}, {"name": "host", "value": "Tushar-Pc"}, {"name": "thread", "value": "18864-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_file_003"}]}